// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xslfechdfetvuxuqnaoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzbGZlY2hkZmV0dnV4dXFuYW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDI2NTEsImV4cCI6MjA3MjE3ODY1MX0.ZSlMnqrTbOdLMEIwl0ltCIIOSih-FMvdUh2ZXd6Fjco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});